nodeLinker: node-modules

npmRegistries:
  //git.aisgorod.ru/api/v4/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: F6B4zLcX5NpUhPoLHTQe

npmScopes:
  ais-gorod:
    npmRegistryServer: "https://git.aisgorod.ru/api/v4/packages/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  eslint-config-react-app@7.0.0:
    dependencies:
      '@babel/plugin-syntax-flow': "^7.14.5"
      '@babel/plugin-transform-react-jsx': "^7.14.9"
  react-dev-utils@12.0.0:
    dependencies:
      typescript: ">=2.7"
      webpack: ">= 4"
  react-scripts@5.0.0:
    dependencies:
      autoprefixer: "^10.0.2"
  recharts@2.1.8:
    dependencies:
      prop-types: "^15.6.0"
  stylelint-config-recommended-scss@5.0.2:
    dependencies:
      postcss: "^8.3.3"
